version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      - SPRING_DATASOURCE_USERNAME=postgres.yksjudnbzkpgmzbtksad
      - SPRING_DATASOURCE_PASSWORD=yuuashura12
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_MAIL_USERNAME=tzyudistira@gmail.com
      - SPRING_MAIL_PASSWORD=lhcu waxx rifj thta
      - JWT_SECRET=ngninep-user-service-super-secret-key-yang-sangat-panjang-untuk-keamanan-jwt-2025
      - JWT_EXPIRATION=3600000
    restart: always

  hotel-service:
    build:
      context: ./hotel-service
      dockerfile: Dockerfile
    container_name: hotel-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      - SPRING_DATASOURCE_USERNAME=postgres.yksjudnbzkpgmzbtksad
      - SPRING_DATASOURCE_PASSWORD=yuuashura12
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=ngninep-user-service-super-secret-key-yang-sangat-panjang-untuk-keamanan-jwt-2025
      - JWT_EXPIRATION=3600000
    restart: always

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      - SPRING_DATASOURCE_USERNAME=postgres.yksjudnbzkpgmzbtksad
      - SPRING_DATASOURCE_PASSWORD=yuuashura12
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=ngninep-user-service-super-secret-key-yang-sangat-panjang-untuk-keamanan-jwt-2025
      - JWT_EXPIRATION=3600000
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - hotel-service
      - booking-service
    environment:
      - PORT=8080
      - USER_SERVICE_URL=http://user-service:8081
      - HOTEL_SERVICE_URL=http://hotel-service:8082
      - BOOKING_SERVICE_URL=http://booking-service:8083
    restart: always
