server.port=8083

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ngninep_booking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (HARUS SAMA dengan user-service & hotel-service)
jwt.secret=ngninep-user-service-super-secret-key-yang-sangat-panjang-untuk-keamanan-jwt-2025
jwt.expiration=3600000
