server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.yksjudnbzkpgmzbtksad
spring.datasource.password=yuuashura12
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (HARUS SAMA dengan user-service)
# Dalam production, pindahkan ke environment variable
jwt.secret=ngninep-user-service-super-secret-key-yang-sangat-panjang-untuk-keamanan-jwt-2025
jwt.expiration=3600000

# Path Simpan File Upload
app.file.upload-path=uploads/hotel-service
