-- Seed 100 hotel records.
-- City assignment rotates through existing rows in the cities table.
-- Re-running this file will skip hotels with the same name.

WITH seed_hotels(name, address, type, description, admin_hotel_id, is_featured, is_on_sale, discount_percent, rating) AS (
    VALUES
    ('NgiNep Grand Bandung', 'Jl. Merdeka No. 11, Bandung', 'Bintang 5', 'Hotel premium di pusat kota dengan akses dekat area belanja dan kuliner.', 1, true, true, 12, 4.8),
    ('Awan Senja Dago', 'Jl. Ir. H. Juanda No. 88, Bandung', 'Boutique', 'Penginapan butik dengan suasana tenang dan desain modern.', 1, true, false, 0, 4.6),
    ('Kirana City Hotel', 'Jl. Sudirman No. 24, Jakarta', 'Bintang 4', 'Hotel bisnis dengan fasilitas lengkap untuk perjalanan kerja.', 2, false, true, 10, 4.3),
    ('Lazuardi Suites', 'Jl. Asia Afrika No. 17, Bandung', 'Bintang 4', 'Suite nyaman dengan interior elegan dan layanan ramah.', 2, false, false, 0, 4.2),
    ('Samudra Bali Resort', 'Jl. Pantai Kuta No. 19, Bali', 'Resort', 'Resort tropis dekat pantai dengan suasana liburan yang hangat.', 3, true, true, 15, 4.9),
    ('Teras Malioboro Inn', 'Jl. Malioboro No. 45, Yogyakarta', 'Budget', 'Penginapan praktis dekat pusat wisata dan kuliner.', 3, false, false, 0, 4.1),
    ('Cakrawala Surabaya Hotel', 'Jl. Basuki Rahmat No. 62, Surabaya', 'Bintang 4', 'Hotel perkotaan dengan kamar luas dan akses transportasi mudah.', 4, false, true, 8, 4.4),
    ('Dewata Garden Villa', 'Jl. Raya Ubud No. 33, Bali', 'Villa', 'Villa bernuansa alam dengan taman privat dan area santai.', 4, true, false, 0, 4.7),
    ('Mentari Semarang Hotel', 'Jl. Pemuda No. 71, Semarang', 'Bintang 3', 'Hotel nyaman untuk keluarga dan perjalanan bisnis singkat.', 5, false, true, 9, 4.0),
    ('Mahakam Balikpapan Stay', 'Jl. Jenderal Sudirman No. 9, Balikpapan', 'Bintang 4', 'Hotel modern dekat pusat bisnis dan kawasan industri.', 5, false, false, 0, 4.3),
    ('Andalas Medan Hotel', 'Jl. Gatot Subroto No. 55, Medan', 'Bintang 4', 'Akomodasi strategis dengan nuansa hangat khas kota Medan.', 1, true, true, 11, 4.5),
    ('Sriwijaya Palembang Suites', 'Jl. Demang Lebar Daun No. 20, Palembang', 'Bintang 4', 'Suite elegan dekat pusat kota dan destinasi kuliner.', 2, false, false, 0, 4.2),
    ('Losari Makassar Hotel', 'Jl. Penghibur No. 12, Makassar', 'Bintang 4', 'Hotel dekat kawasan pantai dan pusat kuliner Makassar.', 3, true, true, 14, 4.6),
    ('Raya Heritage Bandung', 'Jl. Braga No. 7, Bandung', 'Boutique', 'Hotel heritage dengan sentuhan desain klasik dan fasilitas modern.', 4, true, false, 0, 4.7),
    ('Urban Nest Jakarta', 'Jl. Kuningan Persada No. 28, Jakarta', 'Apartment', 'Akomodasi bergaya apartemen untuk staycation dan perjalanan panjang.', 5, false, true, 7, 4.1),
    ('Sagara Kuta Hotel', 'Jl. Kartika Plaza No. 80, Bali', 'Bintang 4', 'Hotel santai dekat pantai dengan akses mudah ke pusat hiburan.', 1, false, true, 13, 4.4),
    ('Amerta Ubud Retreat', 'Jl. Monkey Forest No. 18, Bali', 'Resort', 'Retreat tenang dengan suasana hijau dan pelayanan personal.', 2, true, false, 0, 4.8),
    ('Griya Tugu Yogyakarta', 'Jl. Diponegoro No. 15, Yogyakarta', 'Bintang 3', 'Hotel nyaman dekat stasiun dan ikon kota Yogyakarta.', 3, false, false, 0, 4.0),
    ('Delta Surabaya Inn', 'Jl. Tunjungan No. 10, Surabaya', 'Budget', 'Penginapan hemat dengan lokasi strategis di pusat kota.', 4, false, true, 6, 3.9),
    ('Nusantara Prime Semarang', 'Jl. Pandanaran No. 30, Semarang', 'Bintang 4', 'Hotel elegan dekat pusat oleh-oleh dan kawasan bisnis.', 5, true, false, 0, 4.5),
    ('Borneo Sky Balikpapan', 'Jl. MT Haryono No. 44, Balikpapan', 'Bintang 5', 'Hotel premium dengan pemandangan kota dan fasilitas lengkap.', 1, true, true, 16, 4.8),
    ('Maimun Palace Hotel', 'Jl. Sisingamangaraja No. 21, Medan', 'Boutique', 'Hotel butik dekat kawasan bersejarah dan pusat kuliner.', 2, false, false, 0, 4.2),
    ('Ampera Riverside Hotel', 'Jl. Kapten A. Rivai No. 6, Palembang', 'Bintang 4', 'Hotel dekat sungai dengan suasana kota yang hidup.', 3, false, true, 10, 4.3),
    ('Phinisi Harbor Stay', 'Jl. Nusantara No. 14, Makassar', 'Bintang 3', 'Penginapan nyaman dekat pelabuhan dan pusat kota.', 4, false, false, 0, 4.1),
    ('Citra Dago Residence', 'Jl. Dago Pakar No. 39, Bandung', 'Apartment', 'Residence modern untuk tamu keluarga dan perjalanan panjang.', 5, false, true, 8, 4.2),
    ('Langit Selatan Resort', 'Jl. Pantai Pandawa No. 5, Bali', 'Resort', 'Resort pantai dengan fasilitas rekreasi dan kamar lapang.', 1, true, true, 18, 4.9),
    ('Sedayu Malioboro Hotel', 'Jl. Sosrowijayan No. 8, Yogyakarta', 'Bintang 4', 'Hotel bergaya modern dekat kawasan wisata utama.', 2, true, false, 0, 4.6),
    ('Kota Lama Semarang Inn', 'Jl. Letjen Suprapto No. 22, Semarang', 'Boutique', 'Penginapan estetik dekat kawasan Kota Lama.', 3, false, false, 0, 4.1),
    ('Jembatan Merah Surabaya', 'Jl. Rajawali No. 3, Surabaya', 'Bintang 3', 'Hotel praktis dengan akses mudah ke area historis.', 4, false, true, 5, 3.8),
    ('Mega Kuningan Suites', 'Jl. Mega Kuningan Barat No. 2, Jakarta', 'Bintang 5', 'Suite bisnis premium dengan fasilitas rapat dan lounge.', 5, true, true, 12, 4.7),
    ('Senayan Urban Hotel', 'Jl. Asia Afrika Senayan No. 4, Jakarta', 'Bintang 4', 'Hotel urban dekat pusat olahraga, belanja, dan hiburan.', 1, false, false, 0, 4.4),
    ('Padma Sari Bandung', 'Jl. Riau No. 92, Bandung', 'Bintang 4', 'Hotel kota dengan desain bersih dan suasana nyaman.', 2, false, true, 9, 4.3),
    ('Tanjung Bunga Makassar', 'Jl. Metro Tanjung Bunga No. 15, Makassar', 'Resort', 'Akomodasi santai dengan akses ke kawasan waterfront.', 3, true, false, 0, 4.5),
    ('Sultan Deli Medan', 'Jl. Balai Kota No. 2, Medan', 'Bintang 5', 'Hotel premium di jantung kota dengan layanan eksklusif.', 4, true, true, 14, 4.8),
    ('Kemaro Island Stay', 'Jl. Residen Abdul Rozak No. 31, Palembang', 'Bintang 3', 'Hotel nyaman untuk perjalanan keluarga dan bisnis.', 5, false, false, 0, 4.0),
    ('Pandanaran Comfort Hotel', 'Jl. Pandanaran No. 101, Semarang', 'Budget', 'Penginapan ringkas dengan fasilitas dasar yang bersih.', 1, false, true, 7, 3.9),
    ('Balikpapan Bay Hotel', 'Jl. Pelabuhan Semayang No. 12, Balikpapan', 'Bintang 4', 'Hotel dekat kawasan teluk dengan akses bisnis strategis.', 2, false, false, 0, 4.2),
    ('Royal Braga Bandung', 'Jl. Braga No. 35, Bandung', 'Bintang 5', 'Hotel elegan dekat kawasan seni dan kuliner.', 3, true, true, 15, 4.8),
    ('Seruni Pasteur Hotel', 'Jl. Dr. Djunjunan No. 126, Bandung', 'Bintang 3', 'Hotel transit nyaman dekat akses tol dan bandara.', 4, false, true, 6, 4.0),
    ('Jakarta Garden Residence', 'Jl. Rasuna Said No. 18, Jakarta', 'Apartment', 'Residence lengkap untuk tamu bisnis dan keluarga.', 5, false, false, 0, 4.3),
    ('Cendana Thamrin Hotel', 'Jl. MH Thamrin No. 50, Jakarta', 'Bintang 4', 'Hotel pusat kota dengan akses cepat ke transportasi publik.', 1, false, true, 10, 4.4),
    ('Uluwatu Cliff Resort', 'Jl. Labuan Sait No. 9, Bali', 'Resort', 'Resort tebing dengan suasana eksklusif dan pemandangan laut.', 2, true, true, 20, 4.9),
    ('Sanur Breeze Hotel', 'Jl. Danau Tamblingan No. 40, Bali', 'Bintang 4', 'Hotel santai dekat pantai dan area kuliner.', 3, false, false, 0, 4.5),
    ('Merapi View Lodge', 'Jl. Kaliurang Km 15, Yogyakarta', 'Villa', 'Lodge nyaman dengan suasana pegunungan dan udara sejuk.', 4, true, false, 0, 4.6),
    ('Prawirotaman Boutique', 'Jl. Prawirotaman No. 29, Yogyakarta', 'Boutique', 'Penginapan butik dekat kafe, galeri, dan pusat wisata.', 5, false, true, 8, 4.4),
    ('Tunjungan Premier Hotel', 'Jl. Embong Malang No. 40, Surabaya', 'Bintang 5', 'Hotel premium dekat pusat belanja dan bisnis.', 1, true, true, 13, 4.7),
    ('Kenjeran Beach Stay', 'Jl. Pantai Kenjeran No. 7, Surabaya', 'Bintang 3', 'Akomodasi nyaman dekat kawasan pantai dan wisata keluarga.', 2, false, false, 0, 4.0),
    ('Laweyan Heritage Inn', 'Jl. Laweyan No. 6, Semarang', 'Boutique', 'Hotel heritage dengan nuansa klasik dan kamar nyaman.', 3, false, true, 7, 4.2),
    ('Simpang Lima Suites', 'Jl. Ahmad Yani No. 1, Semarang', 'Bintang 4', 'Suite strategis di pusat aktivitas kota.', 4, true, false, 0, 4.5),
    ('Sepinggan Airport Hotel', 'Jl. Marsma R. Iswahyudi No. 3, Balikpapan', 'Bintang 3', 'Hotel transit dekat bandara dengan layanan cepat.', 5, false, true, 9, 4.1),
    ('Kalimantan Grand Stay', 'Jl. Mulawarman No. 55, Balikpapan', 'Bintang 4', 'Hotel bisnis dengan ruang rapat dan restoran nyaman.', 1, false, false, 0, 4.3),
    ('Toba Urban Medan', 'Jl. Adam Malik No. 22, Medan', 'Bintang 4', 'Hotel modern dekat pusat pemerintahan dan kuliner.', 2, false, true, 8, 4.3),
    ('Kesawan Heritage Hotel', 'Jl. Ahmad Yani Kesawan No. 12, Medan', 'Boutique', 'Hotel butik di kawasan heritage dengan suasana unik.', 3, true, false, 0, 4.6),
    ('Musi River Hotel', 'Jl. Veteran No. 77, Palembang', 'Bintang 4', 'Hotel dengan akses mudah ke pusat kota dan ikon Palembang.', 4, false, true, 11, 4.2),
    ('Palembang City Nest', 'Jl. Jenderal Sudirman No. 110, Palembang', 'Budget', 'Penginapan ekonomis dengan kamar bersih dan praktis.', 5, false, false, 0, 3.9),
    ('Karebosi Prime Makassar', 'Jl. Jenderal Sudirman No. 19, Makassar', 'Bintang 4', 'Hotel dekat pusat kota dan area bisnis Makassar.', 1, true, true, 10, 4.5),
    ('Fort Rotterdam Stay', 'Jl. Ujung Pandang No. 8, Makassar', 'Boutique', 'Penginapan dengan akses dekat kawasan sejarah.', 2, false, false, 0, 4.1),
    ('Ciumbuleuit Hills Hotel', 'Jl. Ciumbuleuit No. 144, Bandung', 'Bintang 4', 'Hotel perbukitan dengan udara sejuk dan pemandangan kota.', 3, true, false, 0, 4.6),
    ('Setiabudi Family Resort', 'Jl. Setiabudi No. 190, Bandung', 'Resort', 'Resort keluarga dengan fasilitas rekreasi lengkap.', 4, false, true, 12, 4.4),
    ('Cikini Arts Hotel', 'Jl. Cikini Raya No. 32, Jakarta', 'Boutique', 'Hotel dekat pusat seni, taman, dan kuliner kota.', 5, false, false, 0, 4.2),
    ('Pondok Indah Suites', 'Jl. Metro Pondok Indah No. 20, Jakarta', 'Bintang 5', 'Suite premium untuk perjalanan keluarga dan bisnis.', 1, true, true, 13, 4.7),
    ('Jimbaran Sunset Resort', 'Jl. Bukit Permai No. 14, Bali', 'Resort', 'Resort nyaman dekat area sunset dan restoran seafood.', 2, true, false, 0, 4.8),
    ('Canggu Surf Stay', 'Jl. Pantai Batu Bolong No. 27, Bali', 'Bintang 3', 'Penginapan santai dekat pantai dan kafe populer.', 3, false, true, 10, 4.3),
    ('Kotagede Boutique Hotel', 'Jl. Kemasan No. 11, Yogyakarta', 'Boutique', 'Hotel kecil dengan desain lokal dan suasana tenang.', 4, false, false, 0, 4.2),
    ('Sleman Garden Villa', 'Jl. Palagan Tentara Pelajar No. 90, Yogyakarta', 'Villa', 'Villa luas untuk keluarga dengan taman privat.', 5, true, true, 9, 4.6),
    ('Gubeng Business Hotel', 'Jl. Gubeng No. 66, Surabaya', 'Bintang 4', 'Hotel bisnis dekat stasiun dan pusat perkantoran.', 1, false, false, 0, 4.3),
    ('Darmo Comfort Suites', 'Jl. Raya Darmo No. 88, Surabaya', 'Bintang 4', 'Suite nyaman di kawasan premium Surabaya.', 2, true, true, 10, 4.5),
    ('Ungaran Valley Hotel', 'Jl. Diponegoro No. 75, Semarang', 'Resort', 'Hotel dengan suasana hijau dan akses mudah ke area wisata.', 3, false, false, 0, 4.2),
    ('Marina Semarang Stay', 'Jl. Marina Raya No. 5, Semarang', 'Bintang 3', 'Penginapan dekat kawasan marina dan bandara.', 4, false, true, 6, 4.0),
    ('Samarinda Road Hotel', 'Jl. Soekarno Hatta No. 18, Balikpapan', 'Budget', 'Hotel ekonomis untuk perjalanan kerja singkat.', 5, false, false, 0, 3.8),
    ('Bukit Damai Balikpapan', 'Jl. Bukit Damai Indah No. 4, Balikpapan', 'Bintang 4', 'Hotel tenang dengan fasilitas kolam dan restoran.', 1, true, true, 12, 4.5),
    ('Polonia Grand Medan', 'Jl. Imam Bonjol No. 15, Medan', 'Bintang 5', 'Hotel premium dekat pusat kota dan kawasan bisnis.', 2, true, false, 0, 4.7),
    ('Ring Road Medan Inn', 'Jl. Gagak Hitam No. 30, Medan', 'Bintang 3', 'Hotel praktis dekat akses ring road dan pusat kuliner.', 3, false, true, 5, 4.0),
    ('Jakabaring Sport Hotel', 'Jl. Gubernur H. Bastari No. 19, Palembang', 'Bintang 4', 'Hotel dekat kawasan olahraga dan acara besar.', 4, false, false, 0, 4.2),
    ('Musi Heritage Inn', 'Jl. Ki Gede Ing Suro No. 8, Palembang', 'Boutique', 'Hotel heritage dengan suasana lokal yang hangat.', 5, true, true, 10, 4.4),
    ('Panakkukang City Hotel', 'Jl. Boulevard Panakkukang No. 21, Makassar', 'Bintang 4', 'Hotel dekat pusat belanja dan kuliner.', 1, false, true, 8, 4.3),
    ('Samata Garden Stay', 'Jl. Hertasning Baru No. 16, Makassar', 'Bintang 3', 'Hotel nyaman dengan akses ke area kampus dan bisnis.', 2, false, false, 0, 4.0),
    ('Lembang Pine Resort', 'Jl. Raya Lembang No. 120, Bandung', 'Resort', 'Resort keluarga di area sejuk dengan nuansa pinus.', 3, true, true, 14, 4.7),
    ('Antapani Urban Hotel', 'Jl. Terusan Jakarta No. 52, Bandung', 'Budget', 'Hotel sederhana dengan akses mudah ke area timur Bandung.', 4, false, false, 0, 3.9),
    ('Kelapa Gading Hotel', 'Jl. Boulevard Raya No. 60, Jakarta', 'Bintang 4', 'Hotel nyaman dekat pusat belanja dan kuliner.', 5, false, true, 9, 4.2),
    ('Kemang Creative Stay', 'Jl. Kemang Raya No. 18, Jakarta', 'Boutique', 'Hotel kreatif dengan suasana hangat dan dekat hiburan.', 1, true, false, 0, 4.5),
    ('Nusa Dua Pearl Resort', 'Jl. Nusa Dua Selatan No. 2, Bali', 'Resort', 'Resort premium dengan fasilitas keluarga dan pantai privat.', 2, true, true, 17, 4.9),
    ('Denpasar Transit Hotel', 'Jl. Teuku Umar No. 41, Bali', 'Bintang 3', 'Hotel transit nyaman dekat pusat kota Denpasar.', 3, false, false, 0, 4.0),
    ('Gejayan Student Hotel', 'Jl. Gejayan No. 25, Yogyakarta', 'Budget', 'Penginapan hemat dekat kampus dan pusat kuliner.', 4, false, true, 6, 3.9),
    ('Keraton Royal Stay', 'Jl. Wijilan No. 3, Yogyakarta', 'Boutique', 'Hotel butik dekat area keraton dan wisata kuliner.', 5, true, false, 0, 4.5),
    ('Mulyosari Family Hotel', 'Jl. Mulyosari No. 77, Surabaya', 'Bintang 3', 'Hotel keluarga dengan akses mudah ke area timur Surabaya.', 1, false, false, 0, 4.0),
    ('CitraLand Surabaya Suites', 'Jl. CitraLand No. 9, Surabaya', 'Apartment', 'Suite apartemen untuk keluarga dan perjalanan panjang.', 2, false, true, 11, 4.3),
    ('Banyumanik Hills Hotel', 'Jl. Setiabudi No. 205, Semarang', 'Bintang 4', 'Hotel perbukitan dengan suasana sejuk dan kamar luas.', 3, true, false, 0, 4.4),
    ('Tembalang Smart Stay', 'Jl. Prof. Sudarto No. 18, Semarang', 'Budget', 'Penginapan praktis dekat kawasan kampus.', 4, false, true, 5, 3.8),
    ('Manggar Beach Hotel', 'Jl. Mulawarman Manggar No. 20, Balikpapan', 'Bintang 3', 'Hotel dekat pantai dengan suasana santai.', 5, false, false, 0, 4.1),
    ('Balikpapan Executive Suites', 'Jl. Jenderal Ahmad Yani No. 25, Balikpapan', 'Bintang 5', 'Suite premium untuk tamu bisnis dan keluarga.', 1, true, true, 13, 4.7),
    ('Merdeka Walk Hotel', 'Jl. Balai Kota No. 6, Medan', 'Bintang 4', 'Hotel dekat pusat kuliner dan area bisnis Medan.', 2, false, true, 8, 4.3),
    ('Kualanamu Transit Inn', 'Jl. Bandara Kualanamu No. 1, Medan', 'Budget', 'Penginapan transit dekat bandara dengan layanan cepat.', 3, false, false, 0, 3.9),
    ('Ilir Timur Hotel', 'Jl. Mayor Ruslan No. 44, Palembang', 'Bintang 3', 'Hotel nyaman dekat area perkantoran dan kuliner.', 4, false, true, 7, 4.0),
    ('Bukit Siguntang Resort', 'Jl. Srijaya Negara No. 12, Palembang', 'Resort', 'Resort hijau dekat kawasan wisata dan ruang keluarga.', 5, true, false, 0, 4.5),
    ('Tamalanrea Business Hotel', 'Jl. Perintis Kemerdekaan No. 30, Makassar', 'Bintang 4', 'Hotel bisnis dekat kawasan kampus dan industri.', 1, false, true, 9, 4.2),
    ('Akkarena Beach Resort', 'Jl. Tanjung Bunga No. 90, Makassar', 'Resort', 'Resort santai dekat pantai dengan fasilitas rekreasi.', 2, true, true, 15, 4.6),
    ('Sukajadi Premium Hotel', 'Jl. Sukajadi No. 100, Bandung', 'Bintang 4', 'Hotel premium dekat pusat belanja dan kuliner keluarga.', 3, false, false, 0, 4.3),
    ('Pancoran Business Stay', 'Jl. Pancoran No. 12, Jakarta', 'Bintang 3', 'Hotel bisnis dengan fasilitas dasar yang lengkap.', 4, false, true, 6, 4.0),
    ('Seminyak Luxe Hotel', 'Jl. Kayu Aya No. 22, Bali', 'Bintang 5', 'Hotel mewah dekat pantai, butik, dan restoran populer.', 5, true, true, 18, 4.9)
),
numbered_hotels AS (
    SELECT
        ROW_NUMBER() OVER () AS row_num,
        *
    FROM seed_hotels
),
city_pool AS (
    SELECT
        id_city,
        ROW_NUMBER() OVER (ORDER BY id_city) AS city_num,
        COUNT(*) OVER () AS city_total
    FROM cities
)
INSERT INTO hotels (
    name,
    city_id,
    address,
    type,
    description,
    admin_hotel_id,
    is_featured,
    is_on_sale,
    discount_percent,
    rating
)
SELECT
    h.name,
    c.id_city,
    h.address,
    h.type,
    h.description,
    h.admin_hotel_id,
    h.is_featured,
    h.is_on_sale,
    h.discount_percent,
    h.rating
FROM numbered_hotels h
JOIN city_pool c
    ON c.city_num = ((h.row_num - 1) % c.city_total) + 1
WHERE NOT EXISTS (
    SELECT 1
    FROM hotels existing
    WHERE existing.name = h.name
);
